-- CLAIM TYPES
-- INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('HOSPITALIZATION', 'Hospitalization Insurance Claim');
-- INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('OUTPATIENT', 'Outpatient Insurance Claim');
-- INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('ACCIDENT', 'Accident Insurance Claim');
-- INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('DENTAL', 'Dental Insurance Claim');
-- INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('OTHER',  'Other Insurance Claim');

INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE, CREATED_AT) VALUES ('VN', DATE '2026-01-01', 'New Year', 'API', SYSTIMESTAMP);
INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE, CREATED_AT) VALUES ('VN', DATE '2026-04-30', 'Reunification Day', 'API', SYSTIMESTAMP);
INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE, CREATED_AT) VALUES ('VN', DATE '2026-09-02', 'National Day', 'API', SYSTIMESTAMP);
INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE, CREATED_AT) VALUES ('SG', DATE '2026-02-17', 'Chinese New Year', 'API', SYSTIMESTAMP);
INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE, CREATED_AT) VALUES ('SG', DATE '2026-02-18', 'Chinese New Year Holiday', 'API', SYSTIMESTAMP);
INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE, CREATED_AT) VALUES ('SG', DATE '2026-04-03', 'Good Friday', 'API', SYSTIMESTAMP);
INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE, CREATED_AT) VALUES ('SG', DATE '2026-08-09', 'National Day', 'API', SYSTIMESTAMP);

INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-001', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-002', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-003', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-004', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-005', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-006', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-007', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-008', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-009', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);
INSERT INTO POLICY (POLICY_NUMBER, STATUS, COUNTRY_CODE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_AT)
VALUES ( 'POL-SG-2026-0010', 'ACTIVE', 'SG', SYSTIMESTAMP, SYSTIMESTAMP + INTERVAL '1' YEAR, SYSTIMESTAMP);

COMMIT;