-- CLAIM TYPES
INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('IP', 'Inpatient Insurance Claim');
INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('OP', 'Outpatient Insurance Claim');
INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('DENTAL', 'Dental Insurance Claim');
INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('HEALTH', 'Health Insurance Claim');
INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('MOTOR',  'Motor Insurance Claim');
INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('LIFE',   'Life Insurance Claim');
INSERT INTO CLAIM_TYPE (CODE, DESCRIPTION) VALUES ('TRAVEL', 'Travel Insurance Claim');

INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE) VALUES ('VN', DATE '2026-01-01', 'New Year', 'GOV');
INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE) VALUES ('VN', DATE '2026-04-30', 'Reunification Day', 'GOV');
INSERT INTO HOLIDAY (COUNTRY_CODE, HOLIDAY_DATE, NAME, SOURCE)VALUES ('VN', DATE '2026-09-02', 'National Day', 'GOV');

COMMIT;