-- CLAIM table indexes
CREATE INDEX IDX_CLAIM_SUBMITTED_AT ON CLAIM(SUBMITTED_AT);

CREATE INDEX IDX_CLAIM_FINAL_DATE ON CLAIM (FINAL_DECISION_AT) LOCAL;

CREATE UNIQUE INDEX UK_CLAIM_NO ON CLAIM (CLAIM_NO) GLOBAL;

CREATE INDEX IDX_CLAIM_TYPE_FINAL ON CLAIM (CLAIM_TYPE, FINAL_DECISION_AT) LOCAL;

CREATE INDEX IDX_CLAIM_TYPE_STATUS_DATE ON CLAIM (CLAIM_TYPE, FINAL_STATUS, FINAL_DECISION_AT) LOCAL;

CREATE INDEX IDX_CLAIM_COUNTRY ON CLAIM (COUNTRY_CODE) LOCAL;

CREATE INDEX IDX_CLAIM_DATE_COUNTRY ON CLAIM (FINAL_DECISION_AT, COUNTRY_CODE) LOCAL;

-- CALENDAR table index
CREATE INDEX IDX_CALENDAR_WORKING_SEQ ON CALENDAR_DIM (WORKING_MIN_SEQ);

-- HISTORY index
CREATE INDEX IDX_STATUS_CLAIM_STATUS ON CLAIM_STATUS_HISTORY (CLAIM_ID, STATUS, STATUS_AT);

CREATE INDEX IDX_STATUS_FINAL ON CLAIM_STATUS_HISTORY (IS_FINAL);

CREATE INDEX IDX_CLAIM_STATUS_FINAL ON CLAIM_STATUS_HISTORY (CLAIM_ID, IS_FINAL);