-- CLAIM table indexes
CREATE INDEX IDX_CLAIM_POLICY ON CLAIM (POLICY_ID) LOCAL;
CREATE INDEX IDX_CLAIM_STATUS ON CLAIM (CLAIM_STATUS) LOCAL;
CREATE INDEX IDX_CLAIM_TYPE_FINAL_DATE ON CLAIM (CLAIM_TYPE, FINAL_DECISION_AT) LOCAL;
CREATE INDEX IDX_CLAIM_DATE ON CLAIM (CLAIM_DATE) LOCAL;
CREATE INDEX IDX_CLAIM_FINAL_DATE ON CLAIM (FINAL_DECISION_AT) LOCAL;
CREATE INDEX IDX_CLAIM_TYPE_STATUS_DATE ON CLAIM (CLAIM_TYPE, CLAIM_STATUS, FINAL_DECISION_AT) LOCAL;

-- CALENDAR table index
CREATE INDEX IDX_CALENDAR_WORKING_SEQ ON CALENDAR_DIM (WORKING_MIN_SEQ);
CREATE INDEX IDX_CALENDAR_DATE ON CALENDAR_DIM (CAL_DATE) LOCAL;

-- HISTORY index
CREATE INDEX IDX_STATUS_CLAIM_STATUS ON CLAIM_STATUS_HISTORY (CLAIM_ID, TO_STATUS, CHANGED_AT);
CREATE INDEX IDX_STATUS_FINAL ON CLAIM_STATUS_HISTORY (IS_FINAL);
CREATE INDEX IDX_HISTORY_CLAIM ON CLAIM_STATUS_HISTORY (CLAIM_ID, CHANGED_AT);
CREATE INDEX IDX_HISTORY_FINAL ON CLAIM_STATUS_HISTORY (CLAIM_ID, IS_FINAL);
CREATE INDEX IDX_HISTORY_STATUS ON CLAIM_STATUS_HISTORY (TO_STATUS);

-- POLICY table index
CREATE INDEX IDX_POLICY_STATUS ON POLICY (STATUS);